version: '3'
services:
  gateway:
    build: .
    ports:
     - "80:8000"
     - "81:8001"
    command: "treeGateway"
    depends_on:
      - "redis"
  redis:
    image: "redis"
    ports:
     - "6379:6379"